# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# Documentation :
# se situer au niveau de ./api/documentation/database
# 1) Pour créer le pdf lancer la commande :
#   $ sphinx-build -b pdf source build
# 2) Pour créer le html lancer la commande :
#   $ sphinx-build -b html source ../../static/build
import os
import sys
sys.path.insert(0, os.path.abspath('../../../'))

# -- Project information -----------------------------------------------------

project = 'Base de données e-NDP'
copyright = '2023, École nationale des chartes'
author = 'L. Terriel, V. Jolivet (École nationale des chartes)'

# The full version, including alpha/beta/rc tags
release = '2.0'
add_module_names = False

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    #'rst2pdf.pdfbuilder'
]
pdf_documents = [
    ('index',
     u'Documentation_db_endp',
     u'Documentation | Base de données e-NDP',
     u'L.Terriel, V. Jolivet - École nationale des chartes/PSL'),
]
pdf_version = '1.0'
pdf_language = "fr_FR"
pdf_break_level = 1
pdf_breakside = "any"
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']