name: eNDP API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVELOPMENT: '1'

    strategy:
      matrix:
        python-version: ['3.9', '3.8']

    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
          tar -xvf sqlite-autoconf-3380500.tar.gz
          ./configure
          make
          sudo make install
          export PATH="/usr/local/bin:$PATH"
        working-directory: sqlite-autoconf-3380500
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
        env:
          LD_LIBRARY_PATH: /usr/local/lib